### ISSUE TITLE
创建订单后无法自动跳转到扫码页

### ISSUE THREAD

**Issue by hiouttime** [hostsoft/whmcs-payment-mianqian#2]
但是等待whmcs跳转到账单后，再次付款可正常跳转

**Comment by ninetian** [comment]
不太清楚你说的是什么

测试的流程
用户下单产品 => WHMCS生成订单 =>  用户点击订单  => 选择码支付 => 点击自动跳转至 码支付 扫码支付 => 返回WHMCS, 完成
