### ISSUE TITLE
whmcs8不回调

### ISSUE THREAD

**Issue by xjh2009** [hostsoft/whmcs-payment-mianqian#3]
![image](https://user-images.githubusercontent.com/102580788/229360643-aafaa19e-ba61-4354-8af2-9291774cb1d5.png)
whmcs7可以正常回调

**Comment by ninetian** [comment]
你开启DEBUG模式
看下啥错误，我来修复下

**Comment by xjh2009** [comment]
![image](https://user-images.githubusercontent.com/102580788/232069402-492256b7-00cf-4b1f-bab7-f592ebb9e55f.png)
这几天比较忙，才回复你，还有一个bug就是vpay回调的orderid是
![image](https://user-images.githubusercontent.com/102580788/232069809-5e4bd337-caaa-4bc7-bc16-7c0e0b05f78e.png)
但是whmcs要回调的是
![image](https://user-images.githubusercontent.com/102580788/232069925-d100e946-b763-43c8-8222-3e4f41a5a5e4.png)

**Comment by xjh2009** [comment]
作者能修吗

**Comment by ninetian** [comment]
等等，最近忙，忙完修

**Comment by ninetian** [comment]
抱歉
我看了下 没修的必要
这个VPAY的服务端升级了,  我部署了一个测试,发现原来不大一样
配置支付二维码啥的地方都没了
原来的APPID啥的 都没了

大致现在就支持支付宝小商户的当面付模式
类似支付宝扫码啥的 对于微信的支持 其它的模式都没了
好像是要大升级啥的


你要是一定要使用这个东西,使用这个仓库里的版本进行部署,测试
不要安装新仓库的最新版本

**Comment by ninetian** [comment]
用这个版本的
这个活的久些，测试支付宝OK，微信没测，应该也无问题
WHMCS模块也开发好了

https://github.com/hostsoft/whmcs_payment_vmq

**Comment by ninetian** [comment]
close
